
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import static javax.print.attribute.Size2DSyntax.MM;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Abd
 */
public class customerCheckIn extends javax.swing.JFrame {

    /**
     * Creates new form customerCheckIn
     */
    
    Connection con;
    
    public customerCheckIn() {
        initComponents();
        
         try {
            con=DriverManager.getConnection( "jdbc:derby://localhost:1527/Assignment","Sumaiya","000000");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),"Error", JOptionPane.INFORMATION_MESSAGE);
        }
         
         
         checkInDateTextField.setEditable(false);
         priceTextField.setEditable(false);
        
         SimpleDateFormat myFormat= new SimpleDateFormat("yyyy/MM/dd");
         Calendar cal = Calendar.getInstance();
         checkInDateTextField.setText(myFormat.format(cal.getTime()));
         
    }
    
    String bed;
    String roomType;
    String roomNo;
    String price;
    
    public void roomDetails(){
        roomNumberComboBox.removeAllItems();
        priceTextField.setText("");
        bed = (String)bedComboBox.getSelectedItem();
        roomType = (String)roomTypeComboBox.getSelectedItem();
        
         try {
            
             String sql= " SELECT * FROM ROOM_INFO where BED_TYPE='"+bed+"' and ROOM_TYPE= '"+roomType+"' and STATUS= 'Not Booked'" ;
             Statement st= con.createStatement();
             ResultSet rs= st.executeQuery(sql);
             
             while(rs.next()){
                 roomNumberComboBox.addItem(rs.getString(1));
             }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),"Error", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mobileNumberTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nationalityTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        genderComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        idProofTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        checkInDateTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        bedComboBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        roomTypeComboBox = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        roomNumberComboBox = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        priceTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Customer Registration & Check IN.png"))); // NOI18N
        jLabel1.setText("CustomerCheckIn");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 168, -1, -1));
        getContentPane().add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 307, 28));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Mobile Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, 20));

        mobileNumberTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(mobileNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 307, 32));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Nationality");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));
        getContentPane().add(nationalityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 307, 29));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Gender");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, -1, -1));

        genderComboBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Femail", "Other" }));
        genderComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(genderComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 307, 31));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Email");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 610, -1, -1));
        getContentPane().add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, 307, 33));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("ID Proof");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 168, -1, -1));
        getContentPane().add(idProofTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 204, 329, 32));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Address");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, -1, -1));
        getContentPane().add(addressTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 336, 329, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Check In Date(Today)");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 444, -1, -1));

        checkInDateTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(checkInDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 474, 320, 31));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Bed");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(946, 168, -1, -1));

        bedComboBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bedComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Triple" }));
        bedComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bedComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(bedComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(946, 201, 312, 36));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Room Type");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 280, -1, -1));

        roomTypeComboBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        roomTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "Non-AC" }));
        roomTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomTypeComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(roomTypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 320, 312, 32));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Room Number");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 400, -1, -1));

        roomNumberComboBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        roomNumberComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomNumberComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(roomNumberComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 440, 322, 31));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Price");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 520, -1, -1));

        priceTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(priceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 560, 322, 31));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Alote Room");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 630, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 630, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Go To Home");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 40, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin Home.png"))); // NOI18N
        jLabel14.setText("jLabel14");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void genderComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderComboBoxActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        int a=  JOptionPane.showConfirmDialog(null, "Do You  want to go to home?","Message", JOptionPane.YES_NO_OPTION);
        if(a==0){
        
                    setVisible(false);
                    new insideApp(). setVisible(true);
    }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
                    setVisible(false);
                    new customerCheckIn(). setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bedComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bedComboBoxActionPerformed
        // TODO add your handling code here:
        
        roomDetails();
        
    }//GEN-LAST:event_bedComboBoxActionPerformed

    private void roomTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomTypeComboBoxActionPerformed
        // TODO add your handling code here:
        
        roomDetails();
        
    }//GEN-LAST:event_roomTypeComboBoxActionPerformed

    private void roomNumberComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomNumberComboBoxActionPerformed
        // TODO add your handling code here:
        
        roomNo = (String)roomNumberComboBox.getSelectedItem();
        try {
            
             String sql= " SELECT * FROM ROOM_INFO where ROOM_NUMBER='"+roomNo+"'" ;
             Statement st= con.createStatement();
             ResultSet rs= st.executeQuery(sql);
             
             while(rs.next()){
                 priceTextField.setText(rs.getString(4));
             }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),"Error", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_roomNumberComboBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int id=1;
        String name= nameTextField.getText();
        String mobileNumber= mobileNumberTextField.getText();
        String nationality= nationalityTextField.getText();
        String email= emailTextField.getText();
        String idProof= idProofTextField.getText();
        String address= addressTextField.getText();
        String checkIn= checkInDateTextField.getText();
        String price= priceTextField.getText();
        String gender = (String)genderComboBox.getSelectedItem();
        String roomNo = (String)roomNumberComboBox.getSelectedItem();
        String bed = (String)bedComboBox.getSelectedItem();
        String roomType = (String)roomTypeComboBox.getSelectedItem();
        
        int row=-1;
        
        try {
           /*
            String sql= " SELECT max(id) FROM CUSTOMER_INFO " ;
             Statement st= con.createStatement();
             ResultSet rs= st.executeQuery(sql);
             
             while(rs.next()){
                 id= rs.getInt(1);
             }
                 id= id+1;
             */
                 if(!price.equals("")){
                     
                   String sql1 ="UPDATE ROOM_INFO SET STATUS='BOOKED' WHERE ROOM_NUMBER = '"+roomNo+"'";                  
                   Statement st1= con.createStatement();
                   row= st1.executeUpdate(sql1);
                   
                   //String sql2= "INSERT INTO CUSTOMER_INFO (ID,NAME,NATIONALITY,MOBILE_NUMBER,GENDER,EMAIL,ADDRESS,ID_PROOF,CHECKIN,ROOMNO,BED,ROOMTYPE,PRICEPERDAY) VALUES ("+id+" , '"+nationality+"','"+mobileNumber+"','"+gender+"','"+email+"','"+address+"','"+idProof+"','"+checkIn+"','"+roomNo+"','"+bed+"','"+roomType+"','"+price+"')" ;
                   String sql2= "INSERT INTO CUSTOMER_INFO (NAME,NATIONALITY,MOBILE_NUMBER,GENDER,EMAIL,ADDRESS,ID_PROOF,CHECKIN,ROOMNO,BED,ROOMTYPE,PRICEPERDAY) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)" ;
                   
                   
                    PreparedStatement ps=con.prepareStatement(sql2);
            
            //ps.setString(1,id);
            ps.setString(1,name);
            ps.setString(2,nationality);
            ps.setString(3,mobileNumber);
            ps.setString(4,gender);
            ps.setString(5,email);
            ps.setString(6,address);
            ps.setString(7,idProof);
            ps.setString(8,checkIn);
            ps.setString(9,roomNo);
            ps.setString(10,bed);
            ps.setString(11,roomType);
            ps.setString(12,price);
            
            
            row= ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Insertion Successfull","Message", JOptionPane.INFORMATION_MESSAGE);
             
                 }
                 
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),"Error", JOptionPane.INFORMATION_MESSAGE);
        }
               
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customerCheckIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTextField;
    private javax.swing.JComboBox<String> bedComboBox;
    private javax.swing.JTextField checkInDateTextField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JTextField idProofTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mobileNumberTextField;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField nationalityTextField;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JComboBox<String> roomNumberComboBox;
    private javax.swing.JComboBox<String> roomTypeComboBox;
    // End of variables declaration//GEN-END:variables
}
