
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Abd
 */
public class customerCheckOut extends javax.swing.JFrame {

    /** Creates new form customerCheckOut */  
    
    Connection con;
    
    public customerCheckOut() {
        initComponents();
        
         try {
            con=DriverManager.getConnection( "jdbc:derby://localhost:1527/Assignment","Sumaiya","000000");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),"Error", JOptionPane.INFORMATION_MESSAGE);
        }
         
         showAll();
         
         customerNameTextField.setEditable(false);
         perDayPaymentTextField.setEditable(false);
         checkInDateTextField.setEditable(false);
         numberOfDaysStayTextField.setEditable(false);
         checkOutDateTextField.setEditable(false);
         totalAmountTextField.setEditable(false);
         mobileNumberTextField.setEditable(false);
         emailTextField.setEditable(false);
        
    }
    
    String roomType;
    String bed;
    String roomNo;
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerInfoTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        customerNameTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        checkInDateTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        checkOutDateTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        mobileNumberTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        perDayPaymentTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        numberOfDaysStayTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        totalAmountTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Customer Check Out.png"))); // NOI18N
        jLabel1.setText("Customer Check Out");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 41, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Go to Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1201, 41, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("ROOM NUMBER");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, -1, 20));

        searchTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(searchTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, 100, 28));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 80, -1, 30));

        customerInfoTable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        customerInfoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Nationality", "Mobile_Number", "Gender", "Email", "Address", "ID_Proof", "CheckIn", "RoomNo", "Bed", "RoomType", "PricePerDay"
            }
        ));
        jScrollPane1.setViewportView(customerInfoTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 1288, 360));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Customer Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, 10));

        customerNameTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(customerNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 178, 285, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Check In Date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, -1, -1));

        checkInDateTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(checkInDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 278, 32));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("CheckOut Date");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 140, -1, -1));

        checkOutDateTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(checkOutDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 170, 241, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Mobile Number");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 130, -1, -1));

        mobileNumberTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(mobileNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 170, 260, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Per Day Payment");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        perDayPaymentTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(perDayPaymentTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 285, 31));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Number Of Days Stay");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, -1, -1));

        numberOfDaysStayTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(numberOfDaysStayTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 278, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Total Amount");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 240, -1, -1));

        totalAmountTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        totalAmountTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalAmountTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(totalAmountTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 270, 241, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Email");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 240, -1, -1));

        emailTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 270, 260, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Check Out");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin Home.png"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int a=  JOptionPane.showConfirmDialog(null, "Do You  want to go to home?","Message", JOptionPane.YES_NO_OPTION);
        if(a==0){
        
                    setVisible(false);
                    new insideApp(). setVisible(true);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
                    setVisible(false);
                    new customerCheckOut(). setVisible(true);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        String roomNo= searchTextField.getText();
        
        try {
            
            String sql= " SELECT * FROM CUSTOMER_INFO where CHECKOUT is NULL and ROOMNO = '"+roomNo+"'" ;
            Statement st= con.createStatement();
            ResultSet rs= st.executeQuery(sql);
            
            if(rs.next()){
                
            searchTextField.setEditable(false);   
                
            customerNameTextField.setText(rs.getString(2));
            mobileNumberTextField.setText(rs.getString(4));
            checkInDateTextField.setText(rs.getString(9));
            perDayPaymentTextField.setText(rs.getString(13));
            emailTextField.setText(rs.getString(6));
            
            SimpleDateFormat myFormat= new SimpleDateFormat("yyyy/MM/dd");
            Calendar cal = Calendar.getInstance();
            checkOutDateTextField.setText(myFormat.format(cal.getTime()));
            
            String dateBeforeString = rs.getString(9);
            java.util.Date dateBefore= myFormat.parse(dateBeforeString);
            String dateAfterString = myFormat.format(cal.getTime());
            java.util.Date dateAfter= myFormat.parse(dateAfterString);
            
            long difference = dateAfter.getTime() - dateBefore.getTime();
            int noOfDaysStay = (int) (difference/(1000*60*60*24));
            
            if(noOfDaysStay == 0){
                noOfDaysStay = 1;
            }
                numberOfDaysStayTextField.setText(String.valueOf(noOfDaysStay));
                float price = Float.parseFloat(perDayPaymentTextField.getText());
                
                totalAmountTextField.setText(String.valueOf(noOfDaysStay*price));
                
            
            
            }else{
                JOptionPane.showMessageDialog(null, "Room is not booked","INFO", JOptionPane.INFORMATION_MESSAGE);
            
            }
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),"Error", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void totalAmountTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalAmountTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalAmountTextFieldActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // TODO add your handling code here:
            int row=-1;
            String name= customerNameTextField.getText();
            String mobileNumber= mobileNumberTextField.getText();
            String email= emailTextField.getText();
            String checkOut= checkOutDateTextField.getText();
            String checkIN= checkInDateTextField.getText();
            String perDayPayment= perDayPaymentTextField.getText();
            String numberOfDayStay= numberOfDaysStayTextField.getText();
            String totalAmount = totalAmountTextField.getText();
            String roomNo= searchTextField.getText();
          /*  String sql1 ="UPDATE CUSTOMER_INFO SET NUMBEROFDAYSSTAY='"+numberOfDayStay+"' , TOTALAMOUNT='"+totalAmount+"' , CHECKOUT='"+checkOut+"' WHERE ROOMNO = '"+roomNo+"'";
            Statement st1= con.createStatement();
            row= st1.executeUpdate(sql1);*/
            
          String sql= "INSERT INTO CUSTOMER_CHECKOUT_INFO (Customer_name , ROOMNO , MOBILE_NUMBER , EMAIL, CHECKIN_DATE , CHECKOUT_DATE , NUMBER_OF_DAYS_STAY , PER_DAY_PAYMENT , TOTALAMOUNT) VALUES (?,?,?,?,?,?,?,?,? )" ;
           
            PreparedStatement ps=con.prepareStatement(sql);
            
            ps.setString(1,name);
            ps.setString(2,roomNo);
            ps.setString(3,mobileNumber);
            ps.setString(4,email);
            ps.setString(5,checkIN);
            ps.setString(6, checkOut);
            ps.setString(7, numberOfDayStay);
            ps.setString(8,perDayPayment);
            ps.setString(9 ,totalAmount );
            
            row= ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Insertion Successfull","Message", JOptionPane.INFORMATION_MESSAGE);
            
           String sql3 ="DELETE FROM CUSTOMER_INFO WHERE ROOMNO = '"+roomNo+"'";                  
                   Statement st3= con.createStatement();
                   row= st3.executeUpdate(sql3);
          
             String sql2 ="UPDATE ROOM_INFO SET STATUS='NOT BOOKED' WHERE ROOM_NUMBER = '"+roomNo+"'";                  
                   Statement st2= con.createStatement();
                   row= st2.executeUpdate(sql2);
                   
                   showAll();
                   
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null, ex.getMessage(),"Error", JOptionPane.INFORMATION_MESSAGE);
            //Logger.getLogger(customerCheckOut.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customerCheckOut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField checkInDateTextField;
    private javax.swing.JTextField checkOutDateTextField;
    private javax.swing.JTable customerInfoTable;
    private javax.swing.JTextField customerNameTextField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mobileNumberTextField;
    private javax.swing.JTextField numberOfDaysStayTextField;
    private javax.swing.JTextField perDayPaymentTextField;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JTextField totalAmountTextField;
    // End of variables declaration//GEN-END:variables

    
     private void showAll() {
        try {
            
            String sql= " SELECT NAME , NATIONALITY , MOBILE_NUMBER , GENDER , EMAIL, ADDRESS , ID_PROOF , CHECKIN , ROOMNO , BED , ROOMTYPE , PRICEPERDAY FROM CUSTOMER_INFO where CHECKOUT is NULL" ;
            Statement st= con.createStatement();
            ResultSet rs= st.executeQuery(sql);
            customerInfoTable.setModel(DbUtils.resultSetToTableModel(rs));
            
            
        } catch (SQLException ex) {
            
            JOptionPane.showMessageDialog(null, "Deta Fetching Failed","Error", JOptionPane.INFORMATION_MESSAGE);
            
           // Logger.getLogger(adminHome.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }
    
}
